#!/usr/bin/python3
# build_catalog.py — source of truth for the Blaque Baux BLOCK derivatives catalog. Encodes the 120 strategy
# building blocks from the Derivatives Master Reference (Kareem Williams / Carter Warrens), emits the
# machine-readable catalog (derivatives_catalog.json), the JSON schema (schema.json), and a human index
# (INDEX.md). No pricing code — this is the taxonomy/backbone the rest of Block hangs off. Run: python build_catalog.py
import json, os, datetime
HERE = os.path.dirname(os.path.abspath(__file__))

# ---- entry helper: keep the source compact but the JSON complete ----
# S(id, name, tag, family, parties, legs, params, settlement, payoff, variants, combos, use, slide, detail="diagram")
def S(id, name, tag, family, parties, legs, params, settlement, payoff, variants, combos, use, slide, detail="diagram"):
    return dict(id=id, name=name, tag=tag, family=family, parties=parties, legs=legs, parameters=params,
                settlement=settlement, payoff=payoff, variants=variants, combinations=combos, use=use,
                deck_slide=slide, detail_level=detail, status="reference")

CATALOG = {}

# ============================== RATES (IRS family + FRA) ==============================
CATALOG["rates"] = [
 S("fra","Forward Rate Agreement","FRA","forward-rate",
   ["Buyer (long / future borrower)","Seller (short / future lender)"],
   [["Seller","Buyer","pays PV of (R_actual - R_fixed) if rates rose"],["Buyer","Seller","pays if rates fell"]],
   ["notional","R_fixed","R_actual (SOFR/EURIBOR)","trade/effective/fixing/settlement dates"],
   "cash, PV-discounted, at settlement (usually effective date)",
   "settlement = notional * (R_actual - R_fixed) * daycount, discounted to PV",
   ["chained FRAs ~ a swap"],["strip of FRAs replicates IRS","hedge a single future funding period"],
   "lock a single future borrowing/lending rate", 2, "full"),
 S("irs_vanilla","Interest Rate Swap","IRS","swap",
   ["Fixed-Rate Payer (A)","Floating-Rate Payer (B)"],
   [["A","B","pays fixed rate"],["B","A","pays floating (SOFR/SONIA/€STR)"]],
   ["notional_principal","fixed(swap) rate","floating reference","tenor","payment frequency","fixing date"],
   "net cash each payment date; principal never exchanged",
   "net = (fixed - floating) * notional * daycount",
   ["average","callable","arrears","OIS","zero-coupon","onshore"],
   ["swap-spread vs treasury","swaption to enter","collar via cap/floor"],
   "core rate hedge/speculation building block", 3, "full"),
 S("irs_average","Average Rate Swap","IRS Average","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays fixed rate"],["Float","Fixed","pays average floating rate over period"]],
   ["notional","fixed rate","floating avg reference","averaging window"],"net cash",
   "float leg = period-average of the reference",["vs vanilla point-fixing"],["smooths fixing risk"],
   "hedge average exposure over a period", 15),
 S("irs_swap_spread","Swap Spread (BGS)","IRS BGS","spread",["Swap-Spread Payer","Swap-Spread Receiver"],
   [["Payer","Receiver","pays IRS rate + spread"],["Receiver","Payer","pays Treasury rate"]],
   ["notional","IRS rate","spread","treasury reference"],"net cash",
   "isolates the swap-spread (IRS - govt)",["cross-currency swap spread (Xccy BGS)"],
   ["trade swap vs govt basis","hedge asset-swap spread"],"trade/hedge the swap-vs-treasury basis", 15),
 S("irs_callable","Callable Swap","IRS Callable","swap+option",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays fixed"],["Float","Fixed","pays floating"],["Fixed","-","right to terminate early"]],
   ["notional","fixed rate","call schedule"],"net cash + optional early termination",
   "IRS + embedded call (Bermudan cancellation)",["cancellable swap"],["= IRS + receiver swaption"],
   "swap with the right to exit early", 15),
 S("irs_arrears","Swap in Arrears","IRS in arrears","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays fixed"],["Float","Fixed","pays floating set in arrears"]],
   ["notional","fixed rate","arrears fixing"],"net cash",
   "floating fixed at END of period (arrears) not start",["vs vanilla (in advance)"],
   ["convexity vs vanilla swap"],"express a view on the forward-rate convexity", 15),
 S("irs_ois","OIS Swap","IRS OIS","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays fixed"],["Float","Fixed","pays compounded overnight rate"]],
   ["notional","fixed rate","overnight index (SOFR/€STR/SONIA)"],"net cash at maturity/periodic",
   "float = compounded O/N over period",["onshore OIS"],["discounting curve / basis vs term rates"],
   "hedge against the O/N funding curve", 16),
 S("irs_ois_onshore","Onshore OIS Swap","IRS OIS Onshore","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays local-currency fixed"],["Float","Fixed","pays local O/N compounded"]],
   ["notional","local fixed rate","local O/N index"],"net cash in local currency",
   "OIS in a restricted/onshore market",["OIS (deliverable)"],["EM local-rates hedge"],
   "onshore/local-market OIS", 17),
 S("treasury_lock","Treasury Lock","Treasury Lock","forward",["Lock Buyer","Lock Seller"],
   [["Buyer/Seller","-","pays based on future Treasury price/yield"]],
   ["notional","reference treasury","lock date"],"cash",
   "locks a future govt-bond yield for issuance",["rate lock","MMD rate lock"],
   ["pre-hedge a bond issuance","vs forward-starting swap"],"lock a future govt funding level", 16),
 S("irs_zero_coupon","Zero Coupon Swap","IRS ZC","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays fixed lump sum at maturity"],["Float","Fixed","pays floating periodically"]],
   ["notional","fixed lump","floating reference"],"one fixed bullet vs periodic floating",
   "fixed side is a single maturity payment",["accreting notional"],["match a zero-coupon liability"],
   "swap a bullet fixed vs periodic floating", 16),
 S("irs_onshore","Onshore IRS","IRS Onshore","swap",["Fixed Payer","Floating Payer"],
   [["Fixed","Float","pays local-currency fixed"],["Float","Fixed","pays local-currency floating"]],
   ["notional","local fixed/floating"],"net cash local currency",
   "vanilla IRS in a restricted market",["IRS (deliverable)"],["EM local-rates hedge"],
   "onshore/local-market IRS", 16),
 S("cap_floor","Cap / Floor","Cap/Floor","option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays if reference > cap strike (or < floor strike)"]],
   ["notional","cap/floor strike","reference","tenor"],"cash on each breach",
   "strip of caplets/floorlets on the reference rate",["collar","straddle","spread"],
   ["cap a floating liability","collar to cheapen"],"bound floating-rate exposure", 15),
 S("collar","Collar","Collar","option-combo",["Buyer","Seller"],
   [["Buyer","-","long cap + short floor (premium often ~0)"]],
   ["cap strike","floor strike","notional"],"cash on breach of either bound",
   "long cap financed by short floor",["zero-cost collar"],["cheapen a cap by giving up downside"],
   "bound rates at low/zero premium", 15),
 S("cap_floor_straddle","Cap/Floor Straddle","Cap/Floor Straddle","option-combo",["Buyer","Seller"],
   [["Buyer","-","long cap + long floor, same strike & dates"]],["strike","notional","dates"],
   "cash on any large rate move","long rate-vol both directions",["strangle (different strikes)"],
   ["harvest/pay rate volatility"],"long interest-rate volatility", 15),
 S("cap_floor_spread","Cap/Floor Spread","Cap/Floor Spread","option-combo",["Investor","Counterparty"],
   [["Investor","-","long cap at strike1 + short cap at strike2"]],["strike1","strike2","notional"],
   "cash within the strike band","capped payoff between two strikes",["put/call spread analog"],
   ["cheapen directional rate view"],"bounded directional rate view", 16),
 S("irs_swaption","Swaption","IRS Cap Floor","swaption",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","grants right to enter an IRS"]],
   ["strike (swap rate)","expiry","underlying swap tenor","payer/receiver"],"physical or cash-settled swap",
   "option to enter a swap",["European","Bermudan","straddle"],
   ["callable/cancellable swaps","hedge issuance optionality"],"optionality on entering a swap", 15),
 S("swaption_european","European Swaption","European Swaption","swaption",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","right to enter IRS on ONE fixed date"]],
   ["strike","single expiry","swap tenor"],"swap on exercise","single-date exercise",
   ["Bermudan","straddle"],["cleanest swap optionality"],"one-date option to enter a swap", 17),
 S("swaption_bermudan","Bermudan Swaption","Bermudan Swaption","swaption",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","right to enter IRS on MULTIPLE fixed dates"]],
   ["strike","exercise dates","swap tenor"],"swap on exercise","multi-date exercise",
   ["European","callable-swap equiv"],["prices callable/cancellable swaps"],"multi-date swap optionality", 17),
 S("swaption_straddle","Straddle Swaption","Straddle Swaption","swaption",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","right to enter IRS as fixed payer OR receiver"]],
   ["strike","expiry","swap tenor"],"swap on exercise","direction-agnostic swaption",
   ["payer/receiver swaptions"],["long swap-rate volatility"],"long rate-vol via swaptions", 17),
 S("xccy_mtm","Mark-to-Market Cross-Currency Swap","Xccy MTM","xccy-swap",["Party A","Party B"],
   [["A","B","Currency A leg + MTM reset"],["B","A","Currency B leg + MTM reset"]],
   ["ccy pair","two rate legs","MTM reset frequency","notionals"],"net cash + periodic notional MTM reset",
   "xccy swap with FX notional resets",["non-MTM","onshore","non-deliverable"],
   ["fund in another currency","basis (xccy) trading"],"cross-currency funding with FX resets", 16),
 S("xccy_non_mtm","Non-MTM Cross-Currency Swap","Xccy non MTM","xccy-swap",["Party A","Party B"],
   [["A","B","Currency A fixed rate"],["B","A","Currency B fixed rate"]],
   ["ccy pair","two fixed legs","notionals"],"net cash; fixed notionals",
   "xccy swap, no FX resets",["MTM","onshore"],["fixed-notional xccy funding"],
   "cross-currency funding, fixed notional", 16),
 S("xccy_swap_spread","Cross-Currency Swap Spread (BGS)","Xccy Swap BGS","xccy-spread",["Spread Payer","Spread Receiver"],
   [["Payer","Receiver","pays XCCY rate + spread"],["Receiver","Payer","pays local IRS rate"]],
   ["ccy pair","xccy rate","spread","local IRS"],"net cash","isolates the cross-currency basis",
   ["swap spread (single ccy)"],["trade the xccy basis"],"trade/hedge the cross-currency basis", 16),
 S("xccy_non_mtm_onshore","Onshore Non-MTM Cross-Currency Swap","Xccy non MTM Onshore","xccy-swap",["Party A","Party B"],
   [["A","B","Local currency A fixed rate"],["B","A","Local currency B fixed rate"]],
   ["ccy pair (restricted)","fixed legs"],"net cash local","onshore xccy swap, fixed notional",
   ["non-MTM (deliverable)"],["EM cross-border funding"],"onshore cross-currency funding", 16),
 S("xccy_nd","Non-Deliverable Cross-Currency Swap","Xccy ND","xccy-swap",["Party A","Party B"],
   [["A","B","USD floating"],["B","A","NDF fixing vs strike, settled in USD"]],
   ["restricted ccy","USD leg","NDF fixings"],"USD cash-settled",
   "xccy swap on a non-deliverable currency",["deliverable xccy"],["EM rates without local access"],
   "cross-currency swap on restricted FX", 17),
]

# ============================== FX (FXD) ==============================
CATALOG["fx"] = [
 S("fx_spot","Spot Transaction","Spot","spot",["Buyer","Seller"],
   [["Buyer","Seller","pays Currency A (spot date)"],["Seller","Buyer","delivers Currency B (spot date)"]],
   ["ccy pair","spot rate","spot date (T+2)"],"physical delivery at spot","exchange at spot",
   ["onshore"],["leg of an FX swap"],"immediate currency exchange", 11),
 S("fx_spot_onshore","Spot Transaction Onshore","Spot Onshore","spot",["Buyer","Seller"],
   [["Buyer","Seller","local currency T+1/T+2"],["Seller","Buyer","delivers FX T+1/T+2"]],
   ["restricted ccy","spot","T+1/T+2"],"onshore delivery","onshore spot",["spot (offshore)"],
   ["EM access"],"onshore spot exchange", 12),
 S("fx_outright_forward","Outright Forward","Outright","forward",["Long Party","Short Party"],
   [["Long","Short","pays agreed forward price"],["Short","Long","delivers underlying asset"]],
   ["ccy pair","forward rate","value date"],"physical/cash at forward date","locked future FX rate",
   ["onshore","average-rate","target","accumulator","NDF"],["hedge future FX exposure"],
   "lock a future FX rate", 10),
 S("fx_outright_onshore","Outright Forward Onshore","Outright Onshore","forward",["Buyer","Seller"],
   [["Buyer","Seller","local currency, agreed future date"],["Seller","Buyer","delivers FX, agreed future date"]],
   ["restricted ccy","forward rate","future date"],"onshore delivery","onshore forward",
   ["outright (offshore)","NDF"],["EM FX hedge"],"onshore forward FX", 12),
 S("fx_avg_rate_forward","Average Rate Forward","Avg Rate Fwd FXD","forward",["Buyer","Seller"],
   [["Buyer","Seller","pays average rate vs agreed forward rate"]],
   ["ccy pair","averaging window","forward rate"],"cash on the average","settles on period-average FX",
   ["average-rate option (Asian)"],["hedge recurring FX flows"],"hedge an average FX exposure", 10),
 S("fx_target_forward","Target Forward","Target Forward FXD","structured-forward",["Client","Bank"],
   [["Client","Bank","FX at better rate if spot stays in range"],["Bank","Client","FX at worse rate if spot breaks barrier"]],
   ["ccy pair","target/range","barrier","knock conditions"],"periodic settlement",
   "enhanced rate with a barrier give-up",["accumulator","pivot"],["cheapen a forward, take barrier risk"],
   "enhanced forward with barrier risk", 12),
 S("fx_forward_accumulator","Forward Accumulator","Fwd Accumulator FXD","structured-forward",["Client","Bank"],
   [["Client","Bank","buys FX daily when spot is below barrier"]],
   ["ccy pair","accumulation level","barrier","schedule"],"daily accumulation",
   "accumulate FX at a favorable level with knock-out",["target forward","decumulator"],
   ["accumulate a position cheaply, barrier risk"],"scheduled accumulation with barrier", 12),
 S("fx_swap","FX Swap","FX Swap","swap",["Party A","Party B"],
   [["A","B","Currency A spot then forward date"],["B","A","Currency B spot then forward date"]],
   ["ccy pair","near/far legs","two value dates"],"two-legged exchange (spot + forward)",
   "spot vs forward exchange (funding/roll)",["onshore","NDF FX swap"],
   ["roll an FX hedge","fund one ccy with another"],"swap currencies spot-vs-forward", 10),
 S("fx_swap_onshore","FX Swap Onshore","FX Swap Onshore","swap",["Party A","Party B"],
   [["A","B","local currency near leg / far leg"],["B","A","FX near leg / far leg"]],
   ["restricted ccy","near/far"],"onshore two-legged","onshore FX swap",["FX swap (offshore)","NDF FX swap"],
   ["EM funding/roll"],"onshore FX swap", 12),
 S("fx_time_option","Time Option (Optional Delivery Forward)","Time Option","forward+option",["Holder","Writer"],
   [["Holder","Writer","chooses delivery date within window"],["Writer","Holder","delivers FX on selected date"]],
   ["ccy pair","forward rate","delivery window"],"physical on chosen date",
   "forward with flexible delivery date",["window forward"],["uncertain settlement timing hedge"],
   "forward with delivery-date optionality", 12),
 S("fx_risk_reversal","Risk Reversal","Risk Rev FXD","option-combo",["Investor","Counterparty"],
   [["Investor","-","long call + short put (or vice versa)"]],
   ["ccy pair","call/put strikes","expiry"],"cash/physical on exercise",
   "directional option combo (skew trade)",["collar","seagull"],
   ["trade FX skew","cheapen directional hedge"],"directional FX view / skew", 11),
 S("fx_straddle","Straddle","Straddle FXD","option-combo",["Investor","Counterparty"],
   [["Investor","-","long call + long put, same strike & expiry"]],["strike","expiry"],
   "cash on any large move","long FX volatility",["strangle"],["harvest/pay FX vol"],
   "long FX volatility", 11),
 S("fx_strangle","Strangle","Strangle FXD","option-combo",["Investor","Counterparty"],
   [["Investor","-","long OTM call + long OTM put"]],["OTM strikes","expiry"],
   "cash on a large move","cheaper long-vol than straddle",["straddle"],["long FX vol, wider break-evens"],
   "long FX volatility (OTM)", 11),
 S("fx_one_touch","One-Touch / No-Touch","Touch FXD","binary-barrier",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays fixed amount if spot touches / does NOT touch barrier"]],
   ["ccy pair","barrier","payout","expiry"],"fixed cash if barrier condition met",
   "binary on touching a barrier",["digital","double-no-touch"],["express a range/breakout view"],
   "binary barrier bet", 11),
 S("fx_simple_barrier","Simple Barrier Option","Simple Barrier FXD","barrier-option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays out if barrier condition is met"]],
   ["ccy pair","strike","barrier (KI/KO)","expiry"],"cash/physical if active",
   "knock-in/knock-out vanilla",["double barrier","digital"],["cheapen a vanilla with a barrier"],
   "barrier-conditioned option", 11),
 S("fx_double_barrier","Double Barrier Option","Double Barrier FXD","barrier-option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays out if EITHER barrier is triggered"]],
   ["ccy pair","two barriers","strike","expiry"],"cash if triggered","two-barrier structure",
   ["single barrier","double-no-touch"],["range/breakout structuring"],"two-barrier option", 12),
 S("fx_avg_rate_option","Average Rate Option (Asian)","Asian FXD","asian-option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays based on average rate vs strike"]],
   ["ccy pair","averaging window","strike","expiry"],"cash on the average",
   "payoff on period-average FX",["average-rate forward"],["hedge recurring flows, cheaper vol"],
   "option on average FX", 12),
 S("fx_digital","Digital Option","Digital Option FXD","binary",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays fixed amount if spot is in/out-of-the-money"]],
   ["ccy pair","strike","payout","expiry"],"fixed cash if ITM","all-or-nothing at a strike",
   ["one-touch","range digital"],["express a precise level view"],"binary at a strike", 12),
 S("fx_vanilla","Vanilla Option","Vanilla Option FXD","option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays intrinsic value if exercised"]],
   ["ccy pair","strike","expiry","call/put"],"cash/physical on exercise","standard FX call/put",
   ["quanto","non-deliverable","barrier","digital"],["building block for combos/hedges"],
   "standard FX option", 13),
 S("fx_quanto","Quanto Option","Quanto Option FXD","option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays in DOMESTIC currency based on FX move"]],
   ["ccy pair","strike","fixed FX conversion","expiry"],"cash in domestic ccy",
   "payoff in domestic ccy at a fixed rate",["vanilla","composite"],["remove FX translation risk"],
   "FX-payoff paid in domestic ccy", 13),
 S("fx_nd_option","Non-Deliverable Option","ND Option FXD","option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","cash settles difference in NDF rate vs strike"]],
   ["restricted ccy","strike","NDF fixing","expiry"],"cash-settled (usually USD)",
   "option on a non-deliverable currency",["onshore ND option","vanilla"],["EM FX optionality w/o access"],
   "option on restricted FX", 13),
 S("fx_nd_option_onshore","Non-Deliverable Option Onshore","ND Opt FXD Onshore","option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","cash settles in local currency"]],
   ["restricted ccy","strike","local fixing"],"cash-settled local","onshore ND option",
   ["ND option (offshore)"],["onshore EM optionality"],"onshore restricted-FX option", 13),
 S("ndf","Non-Deliverable Forward","NDF","forward",["Long Party","Short Party"],
   [["Long","Short","pays notional * agreed NDF rate"],["Short","Long","pays notional * settlement (fixing) rate"]],
   ["restricted ccy","NDF rate","fixing","notional"],"net cash (usually USD)",
   "cash-settled forward on restricted FX",["onshore","NDF swap"],["EM FX hedge without delivery"],
   "cash-settled EM forward", 14),
 S("ndf_onshore","Non-Deliverable Forward Onshore","NDF Onshore","forward",["Long Party","Short Party"],
   [["Long","Short","local currency at agreed NDF rate"],["Short","Long","local currency at settlement rate"]],
   ["restricted ccy","NDF rate","local fixing"],"cash local","onshore NDF",["NDF (offshore)"],
   ["onshore EM hedge"],"onshore cash-settled forward", 14),
 S("ndf_fx_swap","NDF FX Swap","NDF FX Swap","swap",["Party A","Party B"],
   [["A","B","NDF near leg"],["B","A","NDF far leg"]],["restricted ccy","near/far NDF"],
   "net cash","cash-settled FX swap on restricted FX",["onshore NDF swap","FX swap"],
   ["roll an NDF hedge"],"non-deliverable FX swap", 14),
 S("ndf_fx_swap_onshore","NDF FX Swap Onshore","NDF FX Swap Onshore","swap",["Party A","Party B"],
   [["A","B","local currency NDF near leg"],["B","A","local currency NDF far leg"]],
   ["restricted ccy","near/far"],"cash local","onshore NDF swap",["NDF swap (offshore)"],
   ["onshore roll"],"onshore non-deliverable FX swap", 14),
]

# ============================== EQUITY (EQD) ==============================
CATALOG["equity"] = [
 S("eqd_autocall","Autocallable Equity Note","Autocall EQD","structured-note",["Investor","Issuer"],
   [["Investor","Issuer","pays notional"],["Issuer","Investor","coupons if reference at/above barrier"],
    ["Issuer","Investor","if auto-called: notional + final coupon"],["Issuer","Investor","at maturity: worst of performance or notional"]],
   ["reference (single/basket)","coupon barrier","autocall barrier","protection barrier","tenor"],
   "coupons + principal per barrier logic","conditional coupons w/ early redemption + downside barrier",
   ["snowball","phoenix","worst-of basket"],["yield enhancement vs owning the stock","hedge issuer vol book"],
   "conditional-coupon yield note", 8),
 S("eqd_forward","Equity Forward","Forward EQD","forward",["Long Party","Short Party"],
   [["Long","Short","pays agreed forward price"],["Short","Long","delivers underlying shares or cash equivalent"]],
   ["underlying","forward price","value date"],"physical/cash at forward","locked future equity price",
   ["amortizing-strike","accreting-strike"],["synthetic long/short","hedge a future equity flow"],
   "lock a future equity price", 8),
 S("eqd_trs","Total Return Swap (Equity)","TRS EQD","swap",["Total Return Payer","Total Return Receiver"],
   [["Payer (e.g. hedge fund)","Receiver","pays floating (SOFR+spread)"],
    ["Receiver (e.g. investor)","Payer","pays total return of equity/index"]],
   ["underlying/index","financing spread","notional","reset frequency"],"net cash",
   "synthetic financed equity exposure",["commodity TRS","municipal TRS","index TRS"],
   ["gain exposure without ownership","balance-sheet/financing plays"],"financed synthetic equity return", 8),
 S("eqd_amort_strike_fwd","Amortizing Strike Forward","Amort Strike Fwd EQD","forward",["Long Party","Short Party"],
   [["Long","Short","pays pre-determined amortizing strike price"],["Short","Long","delivers underlying shares"]],
   ["underlying","amortization schedule","value date"],"physical/cash",
   "forward with a declining strike schedule",["accreting-strike"],["structured buyback/hedge"],
   "forward w/ amortizing strike", 8),
 S("eqd_asian","Asian Option (Equity)","Asian Option EQD","asian-option",["Option Buyer","Option Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays based on difference between average price & strike"]],
   ["underlying","averaging window","strike","expiry"],"cash on the average","payoff on average price",
   ["average-strike","average-rate"],["hedge average execution (VWAP-like)"],"option on average equity price", 8),
 S("eqd_asr","Accelerated Share Repurchase","ASR EQD","buyback",["Corporation","Investor/Bank"],
   [["Corp","Bank","pays upfront for initial shares"],["Bank","Corp","delivers initial share tranche"],
    ["Corp/Bank","-","final settlement based on average VWAP over the period"]],
   ["buyback notional","VWAP window","discount"],"shares + VWAP true-up","accelerated buyback vs VWAP",
   ["collared ASR","VWAP-minus"],["corporate buyback execution","bank hedges w/ borrow"],
   "accelerated buyback vs VWAP", 8),
 S("eqd_fwd_start_option","Forward Start Option","Fwd Start Option EQD","option",["Option Buyer","Option Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","option strike set at-the-money on a future start date"]],
   ["underlying","start date","expiry"],"cash/physical on exercise","strike set later, ATM at start",
   ["cliquet (series of forward-starts)"],["employee-option / deferred hedging"],"deferred-strike option", 9),
 S("eqd_accr_strike_fwd","Accreting Strike Forward","Accr Strike Fwd EQD","forward",["Long Party","Short Party"],
   [["Long","Short","pays pre-determined accreting strike price"],["Short","Long","delivers underlying shares"]],
   ["underlying","accretion schedule"],"physical/cash","forward w/ rising strike schedule",
   ["amortizing-strike"],["structured financing/hedge"],"forward w/ accreting strike", 9),
 S("eqd_cliquet","Cliquet Option","Cliquet EQD","option",["Option Buyer","Option Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays sum of capped periodic returns"]],
   ["underlying","reset frequency","local/global caps & floors"],"cash on locked periodic returns",
   "ratchet of periodic forward-start options",["reverse cliquet","napoleon"],
   ["structured-note payoff","path-dependent vol view"],"ratcheting periodic-return option", 9),
 S("eqd_var_contingent","Variance Contingent Swap","Var Contingent EQD","variance",["Variance Buyer","Variance Seller"],
   [["Buyer","Seller","pays fixed leg"],["Seller","Buyer","pays realized variance IF barrier is breached"]],
   ["underlying","variance strike","barrier","window"],"cash conditional on barrier",
   "variance swap conditioned on a barrier",["conditional-var","corridor-var"],
   ["conditional vol exposure","cheaper than plain var swap"],"barrier-conditioned variance", 9),
 S("eqd_volatility_swap","Volatility Swap","Volatility EQD","variance",["Vol Buyer","Vol Seller"],
   [["Buyer","Seller","pays fixed vol (notional * strike vol)"],["Seller","Buyer","pays realized vol (notional * realized vol)"]],
   ["underlying","vol strike","vega notional","window"],"cash on realized vol",
   "pure exposure to realized volatility",["variance swap (convex)"],["trade vol without options delta"],
   "trade realized volatility", 9),
 S("eqd_variance_swap","Variance Swap","Variance Swap EQD","variance",["Variance Buyer","Variance Seller"],
   [["Buyer","Seller","pays fixed variance (notional * strike var)"],["Seller","Buyer","pays realized variance (notional * realized var)"]],
   ["underlying","variance strike","var notional","window"],"cash on realized variance",
   "convex exposure to realized variance",["vol swap (linear)","conditional/corridor var"],
   ["harvest variance-risk premium","convexity vs vol swap"],"trade realized variance (convex)", 9),
 S("eqd_conditional_var","Conditional Variance Swap","Cond Var Swap EQD","variance",["Variance Buyer","Variance Seller"],
   [["Buyer","Seller","pays fixed variance"],["Seller","Buyer","pays realized variance ONLY if option expires ITM"]],
   ["underlying","variance strike","condition (ITM)","window"],"cash conditional on ITM",
   "variance accrues only under a condition",["corridor variance","var-contingent"],
   ["cheapen a var-swap with a condition"],"conditionally-accruing variance", 9),
 S("eqd_bespoke_option","Bespoke Option","Bespoke Option EQD","option",["Option Buyer","Option Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays based on custom payoff formula"]],
   ["underlying(s)","custom payoff function","expiry"],"cash per bespoke formula",
   "arbitrary structured payoff",["basket","rainbow","worst-of/best-of"],
   ["tailor an exact exposure/hedge"],"custom-payoff option", 9),
 S("eqd_barrier","Barrier Option (Equity)","Barrier Option EQD","barrier-option",["Option Buyer","Option Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","pays out if barrier is triggered"]],
   ["underlying","strike","barrier (KI/KO)","expiry"],"cash/physical if active",
   "knock-in/knock-out equity option",["double barrier","digital"],["cheapen a vanilla with a barrier"],
   "barrier-conditioned equity option", 10),
 S("eqd_deposit_strategy","Deposit-Based Strategy","Depo Strategy EQD","structured-deposit",["Investor","Bank"],
   [["Investor","Bank","deposits cash"],["Bank","Investor","pays interest + equity-linked return"]],
   ["deposit notional","participation","reference","tenor"],"principal + linked return",
   "principal deposit + equity participation",["capital-protected note","dual-currency deposit"],
   ["yield pickup w/ protection"],"equity-linked deposit", 10),
]

# ============================== CREDIT ==============================
CATALOG["credit"] = [
 S("cds_single","Credit Default Swap (Single-Name)","CDS Single","credit-swap",
   ["Protection Buyer","Protection Seller"],
   [["Buyer","Seller","periodic premium = spread * notional * daycount"],
    ["Seller","Buyer","on credit event: notional * (100% - recovery)"]],
   ["reference entity","reference obligation","notional","credit spread (bps)","credit event defs","recovery"],
   "premium leg + contingent protection leg","insurance on a single entity's default",
   ["index CDS","CDS option"],["hedge a bond/loan exposure","curve & basis (CDS-bond) trades"],
   "single-name credit protection", 4, "full"),
 S("cds_index","Credit Default Swap (Index)","CDS Index","credit-swap",
   ["Protection Buyer","Protection Seller"],
   [["Buyer","Seller","fixed running coupon (e.g. 100bps) + upfront adjustment"],
    ["Seller","Buyer","per-constituent: notional/N * (100% - recovery), name removed, index continues"]],
   ["index (CDX/iTraxx)","N constituents","fixed coupon","upfront","6m roll","recovery"],
   "premium leg + waterfall per default","standardized basket credit protection (waterfall)",
   ["single-name CDS","index option","tranches"],["hedge portfolio credit","macro credit view","index vs intrinsics"],
   "diversified credit protection", 6, "full"),
 S("cds_index_option","CDS Index Option","CDS Index Option","credit-option",["Buyer","Seller"],
   [["Buyer","Seller","pays premium"],["Seller","Buyer","right to buy/sell index protection at a strike spread"]],
   ["index","strike spread","expiry","payer/receiver"],"enters index CDS on exercise",
   "option on credit-index spread",["payer/receiver swaptions on credit"],
   ["hedge credit-spread vol","express spread direction"],"optionality on credit spreads", 7),
 S("rpa","Rate Participation Agreement","RPA","structured-rate",["Buyer","Seller"],
   [["Buyer","Seller","pays premium/fee"],["Seller","Buyer","participation in a reference rate move"]],
   ["reference rate","participation rate","cap/floor","tenor"],"cash on rate participation",
   "structured participation in a rate",["cap/floor","collar"],["tailored rate exposure w/ participation"],
   "structured rate participation", 7),
 S("trs","Total Return Swap (generic)","TRS","swap",["Total Return Payer","Total Return Receiver"],
   [["Payer","Receiver","pays financing (floating + spread)"],["Receiver","Payer","pays total return of the asset"]],
   ["reference asset","financing spread","notional","reset"],"net cash",
   "synthetic financed exposure to any asset",["equity TRS","commodity TRS","municipal TRS","bond TRS"],
   ["off-balance-sheet exposure","financing arbitrage"],"generic financed total return", 7),
]

# ============================== COMMODITY (COM) ==============================
CATALOG["commodity"] = [
 S("com_future","Futures Contract","Future COM","future",["Long Position","Short Position"],
   [["Long","Clearing House","pays daily variation margin"],["Short","Clearing House","pays daily variation margin"]],
   ["underlying commodity","contract size","expiry","initial/variation margin"],"daily mark-to-market via clearing",
   "exchange-traded, cleared, marked daily","standardized future on a commodity",
   ["roll strategies","calendar spreads"],["hedge commodity price","roll-yield / carry (see funding-carry sleeve)"],
   "cleared commodity future", 10),
 S("com_trs","Total Return Swap (Commodity)","TRS COM","swap",["Total Return Payer","Total Return Receiver"],
   [["Payer","Receiver","pays financing (floating + spread)"],["Receiver","Payer","pays total return of the commodity/index"]],
   ["commodity/index","financing spread","notional","reset"],"net cash",
   "synthetic financed commodity exposure",["equity TRS","excess-return vs total-return"],
   ["commodity exposure without futures roll ops","index access"],"financed synthetic commodity return", 7),
]

# ============================== MUNICIPAL ==============================
CATALOG["municipal"] = [
 S("muni_trs","Municipal Total Return Swap","Muni TRS","swap",["TRS Payer","TRS Receiver"],
   [["Payer","Receiver","pays floating rate + asset depreciation"],["Receiver","Payer","pays total return of municipal bond"]],
   ["municipal bond/index","financing","notional","reset"],"net cash",
   "synthetic financed muni-bond exposure",["MMD TRS","equity/commodity TRS"],
   ["muni leverage/financing","tax-aware exposure"],"financed municipal-bond return", 14),
 S("mmd_trs","MMD (Municipal Market Data) TRS","MMD TRS","swap",["TRS Payer","TRS Receiver"],
   [["Payer","Receiver","pays floating rate + MMD spread"],["Receiver","Payer","pays MMD index total return"]],
   ["MMD index","spread","notional","reset"],"net cash","exposure to the MMD muni benchmark",
   ["muni TRS"],["hedge/express muni-curve views"],"synthetic MMD-index return", 14),
 S("mmd_rate_lock","MMD Rate Lock","MMD Rate Lock","forward",["Borrower (Issuer)","Bank"],
   [["Borrower/Bank","-","locks MMD rate for a future bond issuance"]],
   ["MMD reference","lock level","issuance date"],"cash settle at issuance",
   "pre-hedge a future muni issuance rate",["treasury lock","forward-starting swap"],
   ["issuer pre-hedge","rate-lock the deal"],"lock a future muni issuance rate", 14),
 S("muni_fees","Municipal Fees","Muni Fees","fee",["Issuer","Underwriter"],
   [["Issuer","Underwriter","pays underwriting fees & expenses"]],
   ["deal size","fee schedule"],"fee payment","primary-issuance underwriting economics",
   [],["models the cost layer of muni deals"],"muni underwriting fee structure", 14),
]

# ============================== FUNDING / DEPOSIT ==============================
CATALOG["funding"] = [
 S("deposit","Deposit","Depo","deposit",["Depositor","Bank"],
   [["Depositor","Bank","lends principal"],["Bank","Depositor","pays principal + interest at maturity"]],
   ["principal","rate","tenor"],"principal + interest at maturity","term deposit / money-market placement",
   ["structured deposit","dual-currency"],["cash management","funding leg of structures"],
   "term deposit", 10),
 S("interaffiliate_loan","Interaffiliate Loan","Interaffiliate Loan","loan",["Entity A (lender)","Entity B (borrower)"],
   [["A","B","lends loan amount"],["B","A","pays interest + principal at maturity"]],
   ["principal","intercompany rate","tenor"],"interest + principal","intra-group funding",
   ["cost-of-funds transfer"],["treasury / transfer pricing"],"intra-group funding", 10),
 S("cost_of_funds","Cost of Funds","COF","funding-benchmark",["Bank","Lender/Depositor"],
   [["Bank","Lender/Depositor","pays interest based on its funding cost"]],
   ["funding-cost benchmark","spread"],"interest at COF","internal funding-cost pass-through",
   ["FTP (funds transfer pricing)"],["price the funding leg of any structure"],
   "funding-cost benchmark", 10),
]

# ============================== CURATED CORE EXPANSION ==============================
# Forty additional reference blocks broaden foundational option, commodity, credit,
# and inflation/rates coverage. Long Call is promoted from the website prototype so
# the public reference and this machine-readable source share the same 120-block count.
def X(id, name, tag, family, parties, legs, params, settlement, payoff, variants, combos, use):
    return S(id, name, tag, family, parties, legs, params, settlement, payoff,
             variants, combos, use, 0, "diagram")

CATALOG["equity"] += [
 X("eqd_long_call","Long Call","Long Call EQD","option",["Call Buyer","Call Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","delivers upside above strike"]],["underlying","strike","premium","expiry"],"cash or physical at exercise","max(S_T - K, 0) - premium",["American","European"],["bull call spread","covered call"],"limited-loss bullish equity exposure"),
 X("eqd_long_put","Long Put","Long Put EQD","option",["Put Buyer","Put Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays downside below strike"]],["underlying","strike","premium","expiry"],"cash or physical at exercise","max(K - S_T, 0) - premium",["American","European"],["protective put","bear put spread"],"limited-loss bearish or protective exposure"),
 X("eqd_covered_call","Covered Call","Covered Call EQD","option-combo",["Stockholder / Call Seller","Call Buyer"],[["Seller","Buyer","grants upside above strike"],["Buyer","Seller","pays premium"]],["shares","call strike","premium","expiry"],"shares delivered if exercised","stock return + premium - call payoff",["buy-write"],["collar","overwrite"],"earn premium while capping equity upside"),
 X("eqd_protective_put","Protective Put","Protective Put EQD","option-combo",["Stockholder / Put Buyer","Put Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","covers losses below strike"]],["shares","put strike","premium","expiry"],"cash or physical protection","stock return + put payoff - premium",["married put"],["collar","put-spread collar"],"retain upside while flooring downside"),
 X("eqd_bull_call_spread","Bull Call Spread","Bull Call Spread EQD","option-combo",["Spread Buyer","Counterparty"],[["Buyer","Counterparty","buys lower-strike call"],["Buyer","Counterparty","sells higher-strike call"]],["lower strike","upper strike","net premium","expiry"],"net cash at expiry","max(S-K1,0)-max(S-K2,0)-premium",["debit call spread"],["risk reversal","call ladder"],"bounded bullish equity exposure"),
 X("eqd_bear_put_spread","Bear Put Spread","Bear Put Spread EQD","option-combo",["Spread Buyer","Counterparty"],[["Buyer","Counterparty","buys higher-strike put"],["Buyer","Counterparty","sells lower-strike put"]],["lower strike","upper strike","net premium","expiry"],"net cash at expiry","max(K2-S,0)-max(K1-S,0)-premium",["debit put spread"],["put-spread collar"],"bounded bearish equity exposure"),
 X("eqd_butterfly","Butterfly Spread","Butterfly EQD","option-combo",["Butterfly Buyer","Counterparty"],[["Buyer","Counterparty","buys wing options"],["Buyer","Counterparty","sells two body options"]],["low strike","body strike","high strike","premium"],"net cash at expiry","long K1, short 2x K2, long K3",["call butterfly","put butterfly"],["iron butterfly","condor"],"defined-risk view that spot finishes near a target"),
 X("eqd_condor","Condor Spread","Condor EQD","option-combo",["Condor Buyer","Counterparty"],[["Buyer","Counterparty","buys outer wings"],["Buyer","Counterparty","sells inner strikes"]],["four strikes","premium","expiry"],"net cash at expiry","four-leg bounded range payoff",["call condor","put condor"],["iron condor","butterfly"],"defined-risk range exposure with a wider body"),
 X("eqd_iron_condor","Iron Condor","Iron Condor EQD","option-combo",["Premium Seller","Counterparty"],[["Seller","Counterparty","sells inner put and call"],["Seller","Counterparty","buys protective wings"]],["four strikes","net credit","expiry"],"net cash at expiry","credit less loss outside protected range",["wide","narrow"],["condor","short strangle with wings"],"limited-risk premium collection inside a range"),
 X("eqd_calendar_spread","Calendar Spread","Calendar EQD","option-combo",["Calendar Buyer","Counterparty"],[["Buyer","Counterparty","sells near-dated option"],["Buyer","Counterparty","buys later-dated option"]],["strike","near expiry","far expiry","net premium"],"two-expiry option settlement","far option value - near option value",["call calendar","put calendar","diagonal"],["term-structure trade"],"express relative implied volatility across expiries"),
 X("eqd_put_spread_collar","Put Spread Collar","Put Spread Collar EQD","option-combo",["Equity Holder","Counterparty"],[["Holder","Counterparty","buys put spread"],["Holder","Counterparty","sells call"]],["put strikes","call strike","premium","expiry"],"net cash plus equity value","equity + put spread - short call",["zero-cost","participating"],["protective put","collar"],"finance partial downside protection by capping upside"),
 X("eqd_lookback","Lookback Option","Lookback EQD","path-option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays using path maximum or minimum"]],["underlying","observation window","fixed/floating strike","expiry"],"cash at expiry","path-extreme payoff less premium",["fixed-strike","floating-strike"],["Asian option","barrier option"],"retain exposure to the most favorable observed price"),
]

CATALOG["commodity"] += [
 X("com_forward","Commodity Forward","Forward COM","forward",["Commodity Buyer","Commodity Seller"],[["Buyer","Seller","pays fixed forward price"],["Seller","Buyer","delivers commodity or cash difference"]],["commodity","quantity","forward price","delivery date"],"physical or cash at maturity","(spot - forward) * quantity",["physical","cash-settled"],["future","basis swap"],"lock a future commodity purchase or sale price"),
 X("com_swap","Commodity Swap","Swap COM","swap",["Fixed-Price Payer","Floating-Price Payer"],[["Fixed","Floating","pays fixed commodity price"],["Floating","Fixed","pays observed floating price"]],["commodity","notional quantity","fixed price","pricing period"],"periodic net cash","(floating - fixed) * quantity",["single-period","multi-period"],["average-price swap","collar"],"convert floating commodity prices to fixed"),
 X("com_option","Commodity Call / Put","Option COM","option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays intrinsic value if exercised"]],["commodity","strike","premium","expiry"],"cash or physical at exercise","vanilla commodity option payoff",["call","put","American","European"],["collar","three-way collar"],"asymmetric commodity price protection"),
 X("com_collar","Commodity Collar","Collar COM","option-combo",["Hedger","Counterparty"],[["Hedger","Counterparty","buys protective option"],["Hedger","Counterparty","sells offsetting option"]],["floor strike","cap strike","quantity","expiry"],"cash on breach of either bound","bounded commodity price",["producer collar","consumer collar"],["three-way collar"],"bound commodity prices at reduced premium"),
 X("com_three_way_collar","Three-Way Commodity Collar","3-Way Collar COM","option-combo",["Hedger","Counterparty"],[["Hedger","Counterparty","buys protective option and sells two options"]],["three strikes","quantity","expiry"],"cash across three strike regions","collar plus sold disaster option",["producer","consumer"],["commodity collar"],"reduce hedge premium by accepting extreme-tail exposure"),
 X("com_crack_spread","Crack Spread","Crack Spread COM","spread",["Refiner / Spread Buyer","Market Counterparty"],[["Buyer","Counterparty","receives refined-product value"],["Buyer","Counterparty","pays crude-oil value"]],["crude leg","gasoline leg","distillate leg","conversion ratios"],"net cash on product-minus-input margin","products value - crude value",["3-2-1","2-1-1"],["futures strip"],"hedge or express refinery margin"),
 X("com_crush_spread","Crush Spread","Crush Spread COM","spread",["Processor / Spread Buyer","Market Counterparty"],[["Buyer","Counterparty","receives meal and oil value"],["Buyer","Counterparty","pays soybean value"]],["soybean leg","meal leg","oil leg","conversion ratios"],"net cash on outputs-minus-input margin","meal + oil value - soybean value",["board crush"],["futures strip"],"hedge or express oilseed processing margin"),
 X("com_calendar_spread","Commodity Calendar Spread","Calendar COM","spread",["Spread Buyer","Spread Seller"],[["Buyer","Seller","buys one delivery month"],["Buyer","Seller","sells another delivery month"]],["near contract","far contract","quantity"],"daily margin and expiry settlement","near price - far price",["bull spread","bear spread"],["storage trade","roll trade"],"express commodity curve and inventory conditions"),
 X("com_basis_swap","Commodity Basis Swap","Basis Swap COM","swap",["Basis Payer","Basis Receiver"],[["Payer","Receiver","pays location or grade A price"],["Receiver","Payer","pays location or grade B price"]],["two references","quantity","pricing window","tenor"],"periodic net cash","reference A - reference B",["location","grade","index basis"],["fixed-floating swap"],"hedge location, grade, or benchmark mismatch"),
 X("com_asian_option","Asian Commodity Option","Asian Option COM","asian-option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays average-price intrinsic value"]],["commodity","strike","averaging dates","expiry"],"cash from average price","max(average - strike, 0) - premium",["average-price","average-strike"],["commodity swap"],"hedge average physical purchase or sale prices"),
 X("com_swing_option","Swing Option","Swing COM","volume-option",["Energy Buyer","Energy Seller"],[["Buyer","Seller","pays premium or contract price"],["Seller","Buyer","delivers buyer-selected daily volume"]],["minimum volume","maximum volume","exercise schedule","price"],"physical delivery with volume choices","optimized value of exercise schedule",["daily","monthly"],["storage option","take-or-pay"],"manage uncertain energy demand and volume"),
 X("com_weather_derivative","Weather Derivative","Weather COM","index-derivative",["Weather Protection Buyer","Protection Seller"],[["Buyer","Seller","pays premium or fixed leg"],["Seller","Buyer","pays from weather-index outcome"]],["weather station","index","strike","period"],"cash settled to weather index","index payout above or below strike",["HDD","CDD","rainfall"],["energy hedge"],"hedge non-tradable weather-driven volume risk"),
]

CATALOG["credit"] += [
 X("cds_tranche","CDS Index Tranche","Index Tranche CRD","credit-tranche",["Protection Buyer","Protection Seller"],[["Buyer","Seller","pays tranche premium"],["Seller","Buyer","covers portfolio loss within attachment and detachment"]],["index","attachment","detachment","notional","spread"],"premium plus tranche loss settlement","loss allocated within tranche band",["equity","mezzanine","senior"],["CDS index","synthetic CDO"],"target a defined layer of portfolio credit loss"),
 X("cds_bespoke_basket","Bespoke CDS Basket","Bespoke Basket CRD","credit-basket",["Protection Buyer","Protection Seller"],[["Buyer","Seller","pays negotiated premium"],["Seller","Buyer","covers defined basket credit events"]],["reference names","weights","notional","credit-event terms"],"cash or physical under basket terms","sum of covered basket losses",["first-loss","pro-rata"],["nth-to-default","synthetic CDO"],"customize credit protection across selected names"),
 X("cds_first_to_default","First-to-Default Basket","FTD CRD","credit-basket",["Protection Buyer","Protection Seller"],[["Buyer","Seller","pays basket premium"],["Seller","Buyer","pays on first qualifying default"]],["reference basket","notional","premium","recovery"],"terminates after first covered default","loss on first default",["second-to-default","nth-to-default"],["bespoke basket"],"hedge or sell the first default risk in a basket"),
 X("cds_nth_to_default","Nth-to-Default Basket","Nth-to-Default CRD","credit-basket",["Protection Buyer","Protection Seller"],[["Buyer","Seller","pays basket premium"],["Seller","Buyer","pays when the nth qualifying default occurs"]],["reference basket","n","notional","recovery"],"cash after nth default","loss on nth covered default",["second-to-default","third-to-default"],["first-to-default"],"target portfolio default correlation and sequencing"),
 X("cds_loan","Loan Credit Default Swap","LCDS CRD","credit-swap",["Protection Buyer","Protection Seller"],[["Buyer","Seller","pays periodic spread"],["Seller","Buyer","covers loss on syndicated loan"]],["reference loan","notional","spread","recovery"],"cash or physical after credit event","notional * (1 - loan recovery)",["single-name","index"],["loan TRS"],"hedge default risk of a syndicated loan"),
 X("credit_recovery_swap","Recovery Swap","Recovery Swap CRD","credit-swap",["Fixed-Recovery Payer","Realized-Recovery Payer"],[["Fixed","Realized","pays fixed recovery after default"],["Realized","Fixed","pays realized recovery"]],["reference entity","fixed recovery","notional","maturity"],"contingent cash after default","notional * (realized recovery - fixed recovery)",["digital recovery lock"],["CDS"],"isolate recovery-rate risk from default probability"),
 X("credit_spread_option","Credit Spread Option","Spread Option CRD","credit-option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays from spread beyond strike"]],["reference bond or index","strike spread","expiry","notional"],"cash settled at expiry","spread intrinsic value less premium",["payer","receiver"],["CDS option"],"take asymmetric exposure to credit-spread moves"),
 X("credit_linked_note","Credit-Linked Note","CLN CRD","structured-note",["Note Investor","Issuer / Protection Buyer"],[["Investor","Issuer","pays principal"],["Issuer","Investor","pays enhanced coupon and conditional principal"]],["reference entity","coupon","notional","recovery"],"coupon plus credit-contingent redemption","bond value minus reference credit loss",["single-name","basket"],["funded CDS"],"fund credit protection in note form"),
 X("synthetic_cdo","Synthetic CDO","Synthetic CDO CRD","structured-credit",["Tranche Investor","Protection Buyer / SPV"],[["Investor","SPV","funds or sells tranche protection"],["SPV","Investor","pays premium less allocated credit losses"]],["reference portfolio","tranches","attachment","detachment"],"waterfall-based tranche settlement","portfolio losses allocated by capital structure",["funded","unfunded"],["CDS tranche","bespoke basket"],"redistribute portfolio credit risk into tranches"),
 X("credit_asset_swap","Asset Swap","Asset Swap CRD","bond-plus-swap",["Bond Investor","Swap Counterparty"],[["Investor","Counterparty","pays bond fixed coupon"],["Counterparty","Investor","pays floating rate plus spread"]],["bond","price","floating index","asset-swap spread"],"bond cash flows plus net swap coupons","floating return = index + asset-swap spread",["par","market"],["bond-CDS basis"],"convert fixed-rate bond cash flows into floating spread"),
]

CATALOG["rates"] += [
 X("irs_basis_swap","Interest Rate Basis Swap","Basis Swap IRS","basis-swap",["Index-A Payer","Index-B Payer"],[["A","B","pays floating index A plus spread"],["B","A","pays floating index B"]],["notional","two floating indices","basis spread","tenor"],"periodic net cash","index A + spread - index B",["tenor basis","currency basis"],["OIS versus term rate"],"hedge mismatch between floating-rate indices"),
 X("irs_cms","Constant Maturity Swap","CMS IRS","swap",["CMS Payer","Floating Payer"],[["CMS","Floating","pays long-tenor swap rate"],["Floating","CMS","pays money-market floating rate"]],["notional","CMS tenor","floating index","maturity"],"periodic net cash","CMS fixing - floating fixing",["CMS spread","capped CMS"],["curve steepener"],"express or hedge the shape of the swap curve"),
 X("irs_cms_spread_option","CMS Spread Option","CMS Spread Option IRS","rate-option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays when CMS spread exceeds strike"]],["two CMS tenors","strike","expiry","notional"],"cash settled from fixing spread","max(CMS_long - CMS_short - strike, 0)",["cap","floor","digital"],["curve option"],"take convex exposure to yield-curve shape"),
 X("irs_range_accrual","Range Accrual","Range Accrual IRS","structured-rate",["Coupon Investor","Issuer / Counterparty"],[["Investor","Issuer","provides principal or fixed leg"],["Issuer","Investor","pays coupon for in-range observation days"]],["reference rate","lower bound","upper bound","observation dates"],"periodic conditional coupon","coupon * in-range days / total days",["single-range","dual-range"],["callable note"],"earn conditional carry while rates remain in a range"),
 X("inflation_swap","Zero-Coupon Inflation Swap","ZC Inflation IRS","inflation-swap",["Inflation Payer","Fixed Payer"],[["Inflation","Fixed","pays cumulative realized inflation"],["Fixed","Inflation","pays compounded fixed rate"]],["inflation index","base index","fixed rate","maturity"],"single net cash payment at maturity","notional * (realized index ratio - fixed growth)",["year-on-year","seasonality-adjusted"],["inflation-linked bond hedge"],"exchange cumulative inflation for a fixed rate"),
 X("inflation_cap_floor","Inflation Cap / Floor","Inflation Option IRS","inflation-option",["Option Buyer","Option Seller"],[["Buyer","Seller","pays premium"],["Seller","Buyer","pays when inflation is above cap or below floor"]],["inflation index","strike","notional","expiry"],"cash settled from inflation fixing","inflation option intrinsic value",["year-on-year","zero-coupon"],["inflation collar"],"protect against unexpectedly high or low inflation"),
]

# ---- assemble + emit ----
asset_classes = {
 "rates": "Interest-rate & cross-currency derivatives",
 "fx": "Foreign-exchange derivatives (deliverable, onshore, and non-deliverable)",
 "equity": "Equity derivatives (forwards, structured notes, options, variance/vol)",
 "credit": "Credit derivatives (CDS, index, options, TRS)",
 "commodity": "Commodity derivatives",
 "municipal": "Municipal / MMD derivatives",
 "funding": "Funding, deposit & cost-of-funds instruments",
}
# blocks that now have reference pricing code (pricing/block_pricing.jl, proven in pricing_selftest.jl)
IMPLEMENTED = {"irs_vanilla", "fx_outright_forward", "fx_vanilla", "cds_single"}
all_entries = []
for ac in asset_classes:
    for e in CATALOG.get(ac, []):
        e["asset_class"] = ac                        # stamp each entry so the JSON is self-describing
        e["id"] in IMPLEMENTED and e.__setitem__("status", "implemented")
        if e["id"] == "collar":                      # first combination play tested (research/collar_overlay.jl)
            e["combination_research"] = "collar_overlay.jl — guardrail: SPY Sharpe 1.01->1.39, tail -18% vs -24%, at the cost of upside"
        all_entries.append(e)
doc = {
 "_meta": {
   "title": "Blaque Baux — Block Derivatives Catalog",
   "source": "Derivatives Master Reference (Kareem Williams / Carter Warrens, Blaque Baux initiative)",
   "generated": datetime.date.today().isoformat(),
   "count": len(all_entries),
   "status": "reference taxonomy — no pricing code yet; the backbone Block hangs off",
   "note": "Each entry is a BUILDING BLOCK, not a standalone strategy. Value is in composition "
           "(hedging / arbitrage / combination) and in the engine's governance — none is alpha alone.",
 },
 "asset_classes": asset_classes,
 "strategies": all_entries,
}
with open(os.path.join(HERE, "derivatives_catalog.json"), "w") as f:
    json.dump(doc, f, indent=2)

schema = {
 "$schema": "http://json-schema.org/draft-07/schema#",
 "title": "Blaque Baux Block strategy building-block",
 "type": "object",
 "required": ["id","name","tag","asset_class","family","parties","legs","parameters","payoff","status"],
 "properties": {
   "id": {"type":"string","description":"stable snake_case key"},
   "name": {"type":"string"}, "tag": {"type":"string","description":"deck abbreviation"},
   "asset_class": {"enum": list(asset_classes.keys())},
   "family": {"type":"string","description":"swap|forward|option|variance|barrier|swaption|..."},
   "parties": {"type":"array","items":{"type":"string"}},
   "legs": {"type":"array","description":"cash-flow legs [from,to,flow]","items":{"type":"array"}},
   "parameters": {"type":"array","items":{"type":"string"}},
   "settlement": {"type":"string"}, "payoff": {"type":"string"},
   "variants": {"type":"array","items":{"type":"string"}},
   "combinations": {"type":"array","items":{"type":"string"},"description":"documented hedging/arb/combination plays"},
   "use": {"type":"string"}, "deck_slide": {"type":"integer"},
   "detail_level": {"enum":["full","diagram"]},
   "status": {"enum":["reference","spec","implemented","validated"]},
 },
}
with open(os.path.join(HERE, "schema.json"), "w") as f:
    json.dump(schema, f, indent=2)

# markdown index
lines = ["# Block Derivatives Catalog — Index",
 "", f"*Generated from `build_catalog.py` — {doc['_meta']['count']} strategy building blocks. "
 "Machine-readable source: [`derivatives_catalog.json`](derivatives_catalog.json), schema: "
 "[`schema.json`](schema.json).*", "",
 "> Each entry is a **building block, not a standalone strategy**. None is alpha alone — the value is in "
 "**composition** (hedging / arbitrage / combination) under the engine's governance.", ""]
for ac, desc in asset_classes.items():
    ents = CATALOG.get(ac, [])
    lines += [f"## {ac.title()} — {desc}  ({len(ents)})", "",
              "| id | strategy | tag | family | key legs |", "|---|---|---|---|---|"]
    for e in ents:
        legs = " ; ".join(f"{l[0]}→{l[1]}: {l[2]}" if len(l)==3 else " ".join(l) for l in e["legs"])
        lines.append(f"| `{e['id']}` | {e['name']} | {e['tag']} | {e['family']} | {legs[:90]} |")
    lines.append("")
with open(os.path.join(HERE, "INDEX.md"), "w") as f:
    f.write("\n".join(lines))

print(f"catalog: {doc['_meta']['count']} strategies")
for ac in asset_classes: print(f"  {ac:10s} {len(CATALOG.get(ac,[]))}")
